// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv




import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    // seed: "tsx prisma/seeds/seed.ts",
    // seed: "npx tsx prisma/admin-seed.ts",
  },
  datasource: { 
    url: env("DATABASE_URL"),
  },
});
